---
all:
  children:
    cv_servers_prod:
      hosts:
        cv_atd1:
          ansible_host: automation-workshop-cbus1-25-0e1a98fe-eos.topo.testdrive.arista.com
          cv_collection: v3
          execute_tasks: true
    ATD_LAB_PROD:
      children:
        ATD_FABRIC_PROD:
          children:
            ATD_SPINES_PROD:
              vars:
                type: spine
              hosts:
                s2-spine1:
                  ansible_host: 192.168.0.20
            ATD_LEAFS_PROD:
              vars:
                type: l3leaf
              hosts:
                s2-leaf1:
                  ansible_host: 192.168.0.22
                s2-leaf2:
                  ansible_host: 192.168.0.23
            ATD_TENANTS_NETWORKS_PROD:
              children:
                ATD_LEAFS_PROD:
            ATD_SERVERS_PROD:
              children:
                ATD_LEAFS_PROD:

  vars:
    ansible_user: arista
    ansible_password: "{{ lookup('env', 'PASS') }}"
    ansible_network_os: arista.eos.eos
    # Configure privilege escalation
    ansible_become: true
    ansible_become_method: enable
    # HTTPAPI configuration
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_python_interpreter: $(which python3)
