---
custom_structured_configuration_ethernet_interfaces:
  - name: Ethernet1
    shutdown: true
  - name: Ethernet4
    shutdown: true
  - name: Ethernet5
    shutdown: true
  - name: Ethernet6
    shutdown: true
  - name: Ethernet7
    shutdown: true
  - name: Ethernet8
    shutdown: true
