# Spine Switches
spine:
  defaults:
    platform: cEOSLab
    bgp_as: 65001
    loopback_ipv4_pool: 192.0.255.0/24
    mlag: false
  nodes:
    - name: s1-spine1
      id: 1
      mgmt_ip: 192.168.0.10/24
    - name: s1-spine2
      id: 2
      mgmt_ip: 192.168.0.11/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 192.0.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.0.254.0/24
    uplink_interfaces: [Ethernet2, Ethernet3]
    uplink_switches: [s1-spine1, s1-spine2]
    uplink_ipv4_pool: 172.30.11.0/24
    mlag_interfaces: [Ethernet1, Ethernet6]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    evpn_route_servers: [s1-spine1, s1-spine2, s2-spine1, s2-spine2]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    # filter:
    #   only_vlans_in_use: true
  node_groups:
    - group: LEAF1-DC1
      # filter:
      #   tags: [ special, opzone ]
      bgp_as: 65101
      nodes:
        - name: s1-leaf1
          id: 1
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
        - name: s1-leaf2
          id: 2
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
    - group: LEAF2-DC1
      # filter:
      #   tags: [ opzone ]
      bgp_as: 65102
      nodes:
        - name: s1-leaf3
          id: 3
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
        - name: s1-leaf4
          id: 4
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
    - group: BORDER-DC1
      # filter:
      #   tags: [ special, opzone ]
      bgp_as: 65103
      nodes:
        - name: s1-brdr1
          id: 5
          mgmt_ip: 192.168.0.100/24
          uplink_switch_interfaces: [Ethernet7, Ethernet7]
          # evpn_gateway:
          #   remote_peers:
          #     - hostname: s2-brdr1
          #     - hostname: s2-brdr2
          #   evpn_l2:
          #     enabled: true
          #   evpn_l3:
          #     enabled: true
          #     inter_domain: true
        - name: s1-brdr2
          id: 6
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
          # evpn_gateway:
          #   remote_peers:
          #     - hostname: s2-brdr1
          #     - hostname: s2-brdr2
          #   evpn_l2:
          #     enabled: true
          #   evpn_l3:
          #     enabled: true
          #     inter_domain: true
