---
all:
  children:
    cv_servers_dev:
      hosts:
        cv_atd1:
          ansible_host: partnerevent-1-12612a50-eos.topo.testdrive.arista.com
          cv_collection: v3
          execute_tasks: true
    ATD_LAB_DEV:
      children:
        ATD_FABRIC_DEV:
          children:
            ATD_SPINES_DEV:
              vars:
                type: spine
              hosts:
                s1-spine1:
                  ansible_host: 192.168.0.10
                s1-spine2:
                  ansible_host: 192.168.0.11
            ATD_LEAFS_DEV:
              vars:
                type: l3leaf
              hosts:
                s1-leaf1:
                  ansible_host: 192.168.0.12
                s1-leaf2:
                  ansible_host: 192.168.0.13
                s1-leaf3:
                  ansible_host: 192.168.0.14
                s1-leaf4:
                  ansible_host: 192.168.0.15
            ATD_TENANTS_NETWORKS_DEV:
              children:
                ATD_LEAFS_DEV:
            ATD_SERVERS_DEV:
              children:
                ATD_LEAFS_DEV:

  vars:
    ansible_user: arista
    ansible_password: "{{ lookup('env', 'PASS') }}"
    ansible_network_os: arista.eos.eos
    # Configure privilege escalation
    ansible_become: true
    ansible_become_method: enable
    # HTTPAPI configuration
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_python_interpreter: $(which python3)
