---
port_profiles:
  - profile: TENANT_A
    mode: access
    vlans: "110"

servers:
  - name: host1
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [s1-leaf1, s1-leaf2]
        profile: TENANT_A
