---
- name: Configuration deployment with CVP
  hosts: cv_servers
  connection: local
  gather_facts: false
  tasks:
    - name: Provision CVP with AVD configuration
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'ATD_FABRIC'
        configlets_prefix: 'AVD'
        state: present

# - name: Configuration deployment with CVP
#   hosts: cv_servers_prod
#   connection: local
#   gather_facts: false
#   tasks:
#     - name: Provision CVP with AVD configuration
#       ansible.builtin.import_role:
#         name: arista.avd.eos_config_deploy_cvp
#       vars:
#         container_root: 'ATD_FABRIC_PROD'
#         configlets_prefix: 'AVD_PROD'
#         state: present
