---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Build an ACT topolgy
      ansible.builtin.import_role:
      # import_role:
        name: act_topology_gen
      vars:
        veos_version: 4.29.0.2F
        act_veos_username: cvpadmin
        act_veos_password: cvp123!
        act_generic_user: ansible
        act_generic_password: ansible
        act_ansible_node_ip: 192.168.0.6
        act_cvp_version: 2022.2.0

# act_topology_gen role referenced here:
# https://github.com/natedoot/ansible-avd/tree/act-topology/ansible_collections/arista/avd/roles/act_topology_gen
