---
- name: "Run Fabric states validation"
  hosts: CORE
  connection: local
  gather_facts: false
  tasks:

    - name: Validate Fabric
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
