name: Test the prod network

on:
  push:
    branches:
      - main

jobs:
  test-deploy-prod:
    env:
      net: prod
      PASS: ${{ secrets.PASS }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Hi
        run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v3

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: atd-inventory/prod/group_vars/ atd-inventory/prod/host_vars/
          config_file: .yamllint.yml

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Build prod configs
        run: docker-compose run atd-cicd ansible-playbook playbooks/atd-fabric-build.yml -i atd-inventory/prod/hosts.yml

      - name: Test with Batfish
        run: docker-compose run atd-cicd python3 batfish-test.py

      - name: Push configurations to prod
        run: |
          docker-compose run atd-cicd ansible-playbook playbooks/atd-fabric-provision.yml \
            -i atd-inventory/prod/hosts.yml

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
