name: Test the dev network

on:
  push:

jobs:
  test-deploy-dev:
    env:
      net: dev
      PASS: ${{ secrets.PASS }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible
        run: pip install ansible

      - name: Install Arista AVD
        run: ansible-galaxy collection install arista.avd:>=3.8

      - name: Install AVD Requirements
        run: sudo pip install -r ~/.ansible/collections/ansible_collections/arista/avd/requirements.txt

      - name: Upgrade requests to 2.27.0 or above
        run: pip install requests>=2.27.0 --upgrade

      - name: Checkout
        uses: actions/checkout@v3

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: atd-inventory/group_vars/
          config_file: .yamllint.yml

      - name: Build Configurations
        run: ansible-playbook -i atd-inventory/hosts.yml playbooks/atd-fabric-build.yml

      - name: Deploy Configurations
        run: ansible-playbook -i atd-inventory/hosts.yml playbooks/atd-fabric-provision.yml

      # - name: Run AVD EOS Validate State Playbook against ACT
      #   run: ansible-playbook -i inventory/inventory-dev.yml playbooks/dc-validation.yml
  
      # - name: Upload verification reports to github
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ValidationReport
      #     path: DC-information/reports/ # or path/to/artifact

      # - name: Build and Deploy Production Configurations
      #   run: ansible-playbook -i inventory/inventory-prod.yml playbooks/prod-DC-fabric-deploy.yml

#       - name: Start containers
#         run: docker-compose -f "docker-compose.yml" up -d --build

#       - name: Test with Batfish
#         run: docker-compose run atd-cicd python3 batfish-test.py

#       - name: Push configurations to dev
#         run: docker-compose run atd-cicd ansible-playbook playbooks/atd-fabric-provision.yml

#       - name: Stop containers
#         if: always()
#         run: docker-compose -f "docker-compose.yml" down
